// Each category has its own photo; aliases are used on different selectors.
export const dietArtwork = {
  "Equilibrada": [0, 3],
  "Mediterránea": [2, 10],
  "Vegana": [3, 2],
  "Vegetariana": [1, 3],
  "Sin gluten": "visual-gluten-fast.webp",
  "Sin lactosa": "visual-milk-fast.webp",
  "Hiposódica": "visual-low-salt-fast.webp",
  "Musulmana / Halal": "visual-mosque-real.jpg",
  "Diabética": [2, 6],
  "Hipocalórica": [2, 11],
  "Hipercalórica": [0, 11],
  "Rica en proteínas": [2, 4],
  "Alta en proteína": [2, 4],
  "Rica en proteína": [2, 4],
  "Ganancia muscular": [2, 5],
  "Ganar músculo": [2, 5],
  "Rica en fibra": [1, 4],
  "Baja en fibra": [2, 1],
  "Baja en residuos": [0, 13],
  "Sin azúcar añadido": [0, 14],
  "Mantenimiento": [2, 3],
  "Ayuno intermitente": [3, 0],
  "Pérdida de grasa saludable": [1, 6],
  "Por puntos (equilibrada)": [1, 14],
  "Por puntos": [1, 14],
  "Baja en grasas saturadas": [3, 5],
  "Sin alimento X": [1, 13],
  "Económica": [1, 9],
  "Rica en hierro": [1, 11],
  "Semana rápida": [2, 15],
};
